### ISSUE TITLE
用dockerweb版的思源笔记，这个插件不会自动关闭吗

### ISSUE THREAD

**Issue by risodn** [pakeh2866/sy-plugin-tab-close#1]
在docker版安装了这个插件，但是貌似到了设定时间，不会自动关闭页面？

**Comment by pakeh2866** [comment]
我没有docker版，我回头测试一下。

**Comment by pakeh2866** [comment]
> 在docker版安装了这个插件，但是貌似到了设定时间，不会自动关闭页面？

1.测试了一下这docker功能是正常的。

2.请确认或者再次查看一下设置后，点击**右下角**保存按钮

如果还有问题，可以录制BUG视频。

**Comment by risodn** [comment]
https://github.com/user-attachments/assets/115a8d8e-57bd-4905-8710-da20fbe295a6

录制了一个一分钟视频，打开后标签栏没有变化，不知道是否操作问题？

**Comment by pakeh2866** [comment]
我大概知道是什么问题了，感谢你的帮助！下个版本会修复这个BUG。

**Comment by pakeh2866** [comment]
https://github.com/pakeh2866/sy-plugin-tab-close/releases/tag/v0.4.5 

理论上已完成修复，有空您还愿意使用，欢迎您进行测试

**Comment by risodn** [comment]
> https://github.com/pakeh2866/sy-plugin-tab-close/releases/tag/v0.4.5
> 
> 理论上已完成修复，有空您还愿意使用，欢迎您进行测试

https://github.com/user-attachments/assets/bc97706e-b34b-4501-a137-40afb0a13647

我刚又测试了下，貌似docker版本还是没有反应（没有预期关闭其他标签页）

**Comment by pakeh2866** [comment]
> > https://github.com/pakeh2866/sy-plugin-tab-close/releases/tag/v0.4.5
> > 理论上已完成修复，有空您还愿意使用，欢迎您进行测试
> 
>  20241207_104328_20241207_10453034.mp4 
> 我刚又测试了下，貌似docker版本还是没有反应（没有预期关闭其他标签页）

如果可以的话，打开开发者工具，在控制台那看一下日志的记录
